//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploActi.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeActivity
    {
        public int CodeTimeActivity { get; set; }
        public int ActivitiesCode { get; set; }
        public System.DateTime DateActivity { get; set; }
        public int Hours { get; set; }
        public int IdUser { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual User User { get; set; }
    }
}
